#!/bin/bash
# OLinear baseline
# requires：{AREA_ROOT}/olinear_q/{sal|uo|vo|ssh}_{seq_len|pred_len}_ratio{RATIO_TAG}.npy
#   generated by data/generate_corrmat.py
#   python data/generate_corrmat.py --area-root "${AREA_ROOT}" --lags 8,12,16,24,32,48
#
#   bash scripts/run_olinear.sh
#   bash scripts/run_olinear.sh sal_1_12          # only one --data

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

# 与 run.py 里 sal_1_12 等的 root 一致；corrmat 默认写在 AREA_ROOT/olinear_q/
AREA_ROOT="${AREA_ROOT:-/root/autodl-tmp/data/upsampled/1-12/area3}"
Q_SUBDIR="${Q_SUBDIR:-olinear_q}"
# 与 generate_corrmat.py 默认 train_ratio*base_ratio 一致（文件名里的 ratio0.7）
RATIO_TAG="${RATIO_TAG:-0.7}"

CHECKPOINTS="${CHECKPOINTS:-/root/autodl-tmp/olinear/area3/checkpoints}"
LOG_DIR="${LOG_DIR:-/root/autodl-tmp/olinear/area3/logs}"
RESULTS_DIR="${RESULTS_DIR:-/root/autodl-tmp/olinear/area3/results}"

VARS=(sal_1_12 ssh_1_12 uo_1_12 vo_1_12)
SEQ_LENS=(16 24 32 48)

if [ -n "${1:-}" ]; then
  VARS=("$1")
fi

MODEL="olinear"

q_prefix_for_data() {
  local d="$1"
  echo "${d%%_*}"
}

for SEQ_LEN in "${SEQ_LENS[@]}"; do
  HALF=$((SEQ_LEN / 2))
  LABEL_LEN=$HALF
  PRED_LEN=$HALF
  for VAR in "${VARS[@]}"; do
    QP="$(q_prefix_for_data "${VAR}")"
    Q_IN="${Q_SUBDIR}/${QP}_${SEQ_LEN}_ratio${RATIO_TAG}.npy"
    Q_OUT="${Q_SUBDIR}/${QP}_${PRED_LEN}_ratio${RATIO_TAG}.npy"

    if [ ! -f "${AREA_ROOT}/${Q_IN}" ] || [ ! -f "${AREA_ROOT}/${Q_OUT}" ]; then
      echo "[WARN] Missing Q matrix for ${VAR} (seq=${SEQ_LEN}, pred=${PRED_LEN}):"
      echo "       expect ${AREA_ROOT}/${Q_IN}"
      echo "       and    ${AREA_ROOT}/${Q_OUT}"
      echo "       Run: python data/generate_corrmat.py --area-root ${AREA_ROOT} --lags ...,${SEQ_LEN},...,${PRED_LEN},..."
      echo ""
    fi

    echo "=========================================="
    echo ">>> OLinear  data=${VAR}  seq_len=${SEQ_LEN}  label_len=${LABEL_LEN}  pred_len=${PRED_LEN}"
    echo ">>> Q_in=${Q_IN}  Q_out=${Q_OUT}"
    echo "=========================================="

    python -u run.py \
      --checkpoints "${CHECKPOINTS}" \
      --log_dir "${LOG_DIR}" \
      --results_dir "${RESULTS_DIR}" \
      --model "${MODEL}" \
      --data "${VAR}" \
      --features M \
      --freq w \
      --seq_len "${SEQ_LEN}" \
      --label_len "${LABEL_LEN}" \
      --pred_len "${PRED_LEN}" \
      --q_mat_file "${Q_IN}" \
      --q_out_mat_file "${Q_OUT}" \
      --embed_size "${EMBED_SIZE:-1}" \
      --d_model "${D_MODEL:-128}" \
      --d_ff "${D_FF:-64}" \
      --e_layers "${E_LAYERS:-2}" \
      --dropout "${DROPOUT:-0.1}" \
      --batch_size "${BATCH_SIZE:-32}" \
      --train_epochs "${TRAIN_EPOCHS:-50}" \
      --learning_rate "${LR:-0.0001}" \
      --lradj type3 \
      --patience "${PATIENCE:-5}" \
      --itr "${ITR:-3}"

    echo ""
  done
done

echo ">>> OLinear runs finished."
